version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: newpass123
      MYSQL_DATABASE: hhplus
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

networks:
  default:
    driver: bridge